### ISSUE TITLE
Heart not on profile

### ISSUE THREAD

**Issue by scott-22** [WCI-Computer-Science/WCI-Walks#16]
Should the heart to like yourself be beside on your profile? Right now you need to navigate to the leaderboard

**Comment by awenelo** [comment]
I feel like it's weird to like yourself on the page where you edit your data, which is why it isn't there currently, also there's not really a good spot for it on the profile page, as so much of the displayed stuff changes depending on different factors. Also, how liking is set up right now, by liking/unliking yourself on the profile page, you would be brought to your public page, which could be even more annoying.
